image: gradle:7.4.2-jdk17

stages:
  - deploy

variables:
  GRADLE_USER_HOME: '.gradle'

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

deploy:
  stage: deploy
  script:
    - 'gradle publish'
  only:
    - tags
  except:
    - branches
    - triggers