include:
    -   template: Jobs/SAST.gitlab-ci.yml
    -   template: Security/Secret-Detection.gitlab-ci.yml

stages:
    - test
    - deploy

cache:
    paths:
        - .gradle
        - build

image: openjdk:17-jdk-slim

test:
    stage: test
    script:
        - ./gradlew -v
        - ./gradlew build
    only:
        - branches
    except:
        - main

deploy:
    stage: deploy
    script:
        - ./gradlew -v
        - ./gradlew publish
    only:
        - tags
    except:
        - branches
        - triggers